my_app/community/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import DataRequired, ValidationError, Length

from my_app.models import Profile
from my_app import photos


class ProfileForm(FlaskForm):
    """ Class for the profile form """
    username = StringField(label='Username', validators=[DataRequired(message='Username is required')])
    bio = TextAreaField(label='Bio', description='Write something about yourself')
    photo = FileField('Profile picture', validators=[FileAllowed(photos, 'Images only!')])

    def validate_username(self, username):
        profile = Profile.query.filter_by(username=username.data).first()
        if profile is not None:
            raise ValidationError('Username already exists, please choose another username')


class EditProfileForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    bio = TextAreaField(label='Bio', validators=[Length(min=0, max=140)])
    photo = FileField('Profile picture', validators=[FileAllowed(photos, 'Images only!')])
    submit = SubmitField('Submit')

my_app/community/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required, current_user

from my_app import photos, db
from my_app.community.forms import ProfileForm, EditProfileForm
from my_app.models import Profile, User
# , EditProfileForm
community_bp = Blueprint('community_bp', __name__, url_prefix='/community')


@community_bp.route('/')
@login_required
def index():
    return render_template('community.html')


@community_bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    profile = Profile.query.join(User).filter(User.id == current_user.id).first()
    if profile:
        return redirect(url_for('community_bp.update_profile'))
    else:
        return redirect(url_for('community_bp.create_profile'))


@community_bp.route('/create_profile', methods=['GET', 'POST'])
@login_required
def create_profile():
    form = ProfileForm()  # This should be familiar from login and signup routes in auth
    if request.method == 'POST' and form.validate_on_submit():
        filename = None  # Set the filename for the photo to None since this is the default if the user hasn't chosen to add a profile photo
        if 'photo' in request.files:  # Let's you check the submitted form contains a photo (photo is the field name we used in the ProfileForm class)
            if request.files['photo'].filename != '':  # As long as the filename isn't empty then save the photo
                filename = photos.save(request.files['photo'])  # This saves the photo using the global variable photos to get the location to save to
        p = Profile(username=form.username.data, photo=filename, bio=form.bio.data,
                    user_id=current_user.id)  # Build a new profile to be added to the database based on the fields in the form
        db.session.add(p)  # Add the new Profile to the database session
        db.session.commit()  # This saves the new Profile to the database
        return redirect(url_for('community_bp.display_profiles', username=p.username))
    return render_template('profile.html', form=form)


@community_bp.route('/update_profile', methods=['GET', 'POST'])
@login_required
def update_profile():
    profile = Profile.query.join(User).filter_by(id=current_user.id).first()  # Find the existing profile for this user
    form = ProfileForm(
        obj=profile)  # Pre-populate the form by loading the profile using obj=. This relies on the field names in the Profile class in model matching the field names in the ProfileForm class, otherwise you have to explicitly state each field e.g. if the form used bio and the model used biography you would need to add bio = profile.biography
    if request.method == 'POST' and form.validate_on_submit():
        if 'photo' in request.files:
            filename = photos.save(request.files['photo'])
            profile.photo = filename  # Updates the photo field# Updates the country field
        profile.bio = form.bio.data  # Updates the bio field
        profile.username = form.username.data  # Updates the user field
        db.session.commit()  # Save the changes to the database
        return redirect(url_for('community_bp.display_profiles', username=profile.username))
    return render_template('profile.html', form=form)


@community_bp.route('/display_profiles', methods=['POST', 'GET'])
@community_bp.route('/display_profiles/<username>/', methods=['POST', 'GET'])
@login_required
def display_profiles(username=None):
    results = None
    if username is None:
        if request.method == 'POST':
            term = request.form['search_term']
            if term == "":
                flash("Enter a name to search for")
                return redirect(url_for("community_bp.index"))
            results = Profile.query.filter(Profile.username.contains(term)).all()
    else:
        results = Profile.query.filter_by(username=username).all()
    if not results:
        flash("No users found.")
        return redirect(url_for("community_bp.index"))
    # The following iterates through the results and adds the full url to a list of urls
    urls = []
    for result in results:
        url = photos.url(
            result.photo)  # uses the global photos plus the photo file name to determine the full url path
        urls.append(url)
    return render_template('display_profile.html', profiles=zip(results, urls))  # Note the zip to pass both lists as a parameter


@community_bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('edit_profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', title='Edit Profile',
                           form=form)

my_app/main/routes.py
from pathlib import Path

from flask import Blueprint, render_template, redirect
from flask_login import current_user, login_required
import pandas as pd
import matplotlib.pyplot as plt

main_bp = Blueprint('main_bp', __name__)


@main_bp.route('/', defaults={'name': 'Anonymous'})
@main_bp.route('/<name>')
def index(name):
    if not current_user.is_anonymous:
        name = current_user.firstname
    return render_template('index.html', title="Home page", name=name)


@main_bp.route('/mpl')
@login_required
def mpl():
    data_folder = Path('../data')
    Excel_file = 'international-visitors-london.xlsx'
    data = pd.read_excel(data_folder / Excel_file, sheet_name='Raw data')
    url = create_mpl_chart(data)

    return render_template('chart_mpl.html', url=url, url_=url,title="Pie chart")


def create_mpl_chart(data):
    y = data['mode'].values.tolist()
    a = y.count('Air')
    b = y.count('Sea')
    c = y.count('Tunnel')
    d = a + b + c
    x = [(a / d) * 100, (b / d) * 100, (c / d) * 100]
    label = ['Air', 'Sea', 'Tunnel']
    colors = ['skyblue', 'blue', 'gold']
    _explode = (0.1, 0, 0)

    Purpose = data['purpose'].values.tolist()
    A = Purpose.count('Holiday')
    B = Purpose.count('Business')
    C = Purpose.count('VFR')
    D = Purpose.count('Miscellaneous')
    F = Purpose.count('Study')
    E = A + B + C + D + F
    X = [(A / E) * 100, (B / E) * 100, (C / E) * 100, (D / E) * 100, (F / E) * 100]
    Labels = ['Holiday', 'Business', 'VFR', 'Miscellaneous', 'Study']
    _Explode = (0.1, 0.08, 0.09, 0.07, 0.06)

    fig, (ax1, ax2) = plt.subplots(2,1)

    ax1.pie(x, labels=label, autopct='%1.1f%%', colors=colors, explode=_explode, shadow=True)
    ax2.pie(X, labels=Labels, autopct='%1.2f%%', explode=_Explode, shadow=True)
    fig.tight_layout()
    url = 'static/img/plot.png'
    fig.savefig(url)
    return url


@main_bp.route('/dash_app1')
def dash_app1():
    return redirect('/dash_app1/')

my_app/templates/chart_mpl.html
{% extends 'layout.html' %}
{% block content %}
    <img src={{ url }} class="img-responsive" alt="Pie chart">
{% endblock %}

my_app/templates/community.html
{% extends 'layout.html' %}
{% block content %}
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="https://fonts.googleapis.com/css?family=Oswald:700|Patua+One|Roboto+Condensed:700" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<section id="contact" class="content-section text-center">
        <div class="contact-section">
            <div class="container">
              <h2>Contact Us</h2>

              <div class="row">
                <div class="col-md-8 col-md-offset-2">
                  <form class="form-horizontal">
                    <div class="form-group">
                      <label for="exampleInputName2">Name</label>
                      <input type="text" class="form-control" id="exampleInputName2" placeholder="Enter Name Here">
                    </div>
                    <div class="form-group">
                      <label for="exampleInputEmail2">Email</label>
                      <input type="email" class="form-control" id="exampleInputEmail2" placeholder="Enter E-mail Here">
                    </div>
                    <div class="form-group ">
                      <label for="exampleInputText">Your Message</label>
                     <textarea  class="form-control" placeholder="Description"></textarea>
                    </div>
                    <button type="submit" class="btn btn-default">Send Message</button>
                  </form>

                  <hr>
                    <h3>Our Social Sites</h3>
                  <ul class="list-inline banner-social-buttons">
                    <li><a href="#" class="btn btn-default btn-lg"><i class="fa fa-facebook"> <span class="network-name">Facebook</span></i></a></li>
                    <li><a href="#" class="btn btn-default btn-lg"><i class="fa fa-wordpress"> <span class="network-name">Wordpress</span></i></a></li>
                    <li><a href="#" class="btn btn-default btn-lg"><i class="fa fa-youtube-play"> <span class="network-name">Youtube</span></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
        </div>
      </section>
{% endblock %}

my_app/templates/display_profile.html
{% extends 'layout.html' %}
{% set title = 'Profile Display' %}
{% from "formhelpers.html" import render_field %}
{% block content %}
    {% for result, url in profiles %}
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{{ url }}" alt="User profile photo">
            <div class="card-body">
                <h5 class="card-title">{{ result.username }}</h5>
                <p class="card-text">{{ result.bio }}</p>
            </div>
        </div>
        {% if user == current_user %}
            <p><a href="{{ url_for('edit_profile') }}">Edit your profile</a></p>
        {% endif %}
    {% endfor %}

{% endblock %}

my_app/templates/edit_profile.html
{% extends "layout.html" %}

{% block content %}
    <h1>Edit Profile</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.about_me.label }}<br>
            {{ form.about_me(cols=50, rows=4) }}<br>
            {% for error in form.about_me.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

my_app/templates/formhelpers.html
{% macro render_field(field) %}
    <div class="form-group">
        <dt>{{ field.label }}
        <dd>{{ field(**kwargs)|safe }}
            {% if field.errors %}
                <ul class=errors>
                    {% for error in field.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </dd>
    </div>
{% endmacro %}

my_app/templates/index.html
{% extends 'layout.html' %}
{% block content %}
    <h1>{{ title }}</h1>
    <p>Welcome {{ name }}</p>
    <p>This is the my_app home page.</p>

{% endblock %}

my_app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.css') }}">
    {# Add to the head section #}
    <link rel = "shortcut icon" href ="/my_app/static/img/Logo_coursework.ico"  type = "image/x-icon">
    <title>{{ title }}</title>

</head>
<body>
<header>
    {% include 'navigation.html' %}

</header>
<main>
    {# Displays flashed messages on a page #}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</main>

<script src="{{ url_for('static', filename='js/bootstrap.bundle.js') }}"></script>
</body>
</html>

my_app/templates/login.html
{% extends 'layout.html' %}
{% set title = 'Login' %}
{% from "formhelpers.html" import render_field %}
{% block content %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <form method="POST" action="{{ url_for('auth.login') }}">
                {{ form.csrf_token }}
                <dl>
                    {{ render_field(form.email, class="form-control") }}
                    {{ render_field(form.password, class="form-control") }}
                    {{ render_field(form.remember, class="form-check-input") }}
                </dl>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
    </div>
{% endblock %}

my_app/templates/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>VISITORS LONDON</title>
    <style>
        body {
            background-image: url("/my_app/static/css/London.jpeg");
        }
    </style>
</head>
<body>
{# example navigation.html #}

<nav class="navbar navbar-expand-lg navbar-light bg-light">

    <div class="container-fluid">
        <img alt="recycle logo" style="margin-right:10px" class=img-thumbnail width=50px
             src="{{ url_for('static', filename='img/Logo_coursework.PNG') }}">
        <a class="navbar-brand" href="#">VISITORS LONDON </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for("main_bp.index") }}">Home</a>
                </li>
                <a class="nav-link" href="{{ url_for("community_bp.index") }}">Community</a>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">Charts</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{{ url_for("main_bp.mpl") }}">Pie charts</a></li>
                        <li><a class="dropdown-item" href="{{ url_for("main_bp.dash_app1") }}">Dash app</a></li>
                    </ul>
                </li>
                {% if current_user.is_anonymous %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for("auth.login") }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for("auth.signup") }}">Sign up</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for("community_bp.profile") }}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for("auth.logout") }}">Logout</a>
                    </li>
                {% endif %}
            </ul>
            <form class="d-flex" action="{{ url_for("community_bp.display_profiles") }}" method="post">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"
                       name="search_term">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

</body>
</html>

my_app/templates/navigation.html
{# example navigation.html #}

<nav class="navbar navbar-expand-lg navbar-light bg-light">

    <div class="container-fluid">
        <img alt="recycle logo" style="margin-right:10px" class=img-thumbnail width=50px
             src="{{ url_for('static', filename='img/Logo_coursework.PNG') }}">
        <a class="navbar-brand" href="#">VISITORS LONDON </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for("main_bp.index") }}">Home</a>
                </li>
                    <a class="nav-link" href="{{ url_for("community_bp.index") }}">Community</a>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">Charts</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{{ url_for("main_bp.mpl") }}">Pie charts</a></li>
                        <li><a class="dropdown-item" href="{{ url_for("main_bp.dash_app1") }}">Dash app</a></li>
                    </ul>
                </li>
                {% if current_user.is_anonymous %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for("auth.login") }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for("auth.signup") }}">Sign up</a>
                    </li>
                {% else %}
                     <li class="nav-item">
                         <a class="nav-link" href="{{ url_for("community_bp.profile") }}">Profile</a>
                     </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for("auth.logout") }}">Logout</a>
                    </li>
                {% endif %}
            </ul>
            <form class="d-flex" action="{{ url_for("community_bp.display_profiles") }}" method="post">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"
                           name="search_term">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

my_app/templates/profile.html
{% extends 'layout.html' %}
{% set title = 'Profile' %}
{% from "formhelpers.html" import render_field %}
{% block content %}
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <dl>
            {{ render_field(form.username, class="form-control") }}
            {{ render_field(form.bio, class="form-control") }}
            {{ render_field(form.photo, class="custom-file", id="input_file") }}
        </dl>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}

my_app/templates/signup.html
{% extends 'layout.html' %}
{% from "formhelpers.html" import render_field %}
{% block content %}
    <br>
    <div class="card" style="width: 25rem;">
        <div class="card-body">
            <form method="POST" action="{{ url_for('auth.signup') }}">
                {{ form.csrf_token }}
                <dl>
                    {{ render_field(form.first_name, class="form-control")}}
                    {{ render_field(form.last_name, class="form-control")}}
                    {{ render_field(form.email, class="form-control")}}
                    {{ render_field(form.password, class="form-control")}}
                    {{ render_field(form.password_repeat, class="form-control")}}
                </dl>
                <input type="submit" value="Sign up">
            </form>
        </div>
    </div>
{% endblock %}